Extension { #name : #FAMIXSourcedEntity }

{ #category : #'*Fuhrman-MooseHerder' }
FAMIXSourcedEntity >> astStartPosition [
	<MSEProperty: #astStartPosition type: #Number>
	<MSEComment: 'Start position of AST node, exported by JDT2MSE'>
]

{ #category : #'*Fuhrman-MooseHerder' }
FAMIXSourcedEntity >> astStartPosition: aNumber [

]

{ #category : #'*Fuhrman-MooseHerder' }
FAMIXSourcedEntity >> astStopPosition [
	<MSEProperty: #astStopPosition type: #Number>
	<MSEComment: 'Stop position of AST node, exported by JDT2MSE'>

]

{ #category : #'*Fuhrman-MooseHerder' }
FAMIXSourcedEntity >> astStopPosition: aNumber [
]
