Extension { #name : #SequenceableCollection }

{ #category : #'*GitMiner' }
SequenceableCollection >> eighteenth [
	"Answer the eightteenth element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 18
]

{ #category : #'*GitMiner' }
SequenceableCollection >> eleventh [
	"Answer the eleventh element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 11
]

{ #category : #'*GitMiner' }
SequenceableCollection >> fifteenth [
	"Answer the fifteenth element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 15
]

{ #category : #'*GitMiner' }
SequenceableCollection >> fourteenth [
	"Answer the fourteenth element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 14
]

{ #category : #'*GitMiner' }
SequenceableCollection >> nineteenth [
	"Answer the nineteenth element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 19
]

{ #category : #'*GitMiner' }
SequenceableCollection >> seventeenth [
	"Answer the seventeenth element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 17
]

{ #category : #'*GitMiner' }
SequenceableCollection >> sixteenth [
	"Answer the sixteenth element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 16
]

{ #category : #'*GitMiner' }
SequenceableCollection >> tenth [
	"Answer the tenth element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 10
]

{ #category : #'*GitMiner' }
SequenceableCollection >> thirteenth [
	"Answer the thirteenth element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 13
]

{ #category : #'*GitMiner' }
SequenceableCollection >> twelvth [
	"Answer the twelvth element of the receiver.
	Raise an error if there are not enough elements."

	^ self at: 12
]
