@startuml
skinparam defaultFontName Arial
title Example of an empirical analysis pipeline
skinparam style strictuml
|Pharo|
start
:git clone (Iceberg);
:local git repository
of Java code]
:filterCommitsLeftBranch;
:Commit Metadata]
:selectCommits;
:Selected subset of commits]
:generatePairsAndTransactions;
:pairs and transactions]
|#antiquewhite|Git|
:Extract commit startOID;
:temp directory startOID]
|Java|
:generate MSE file for startOID;
:startOID.mse]
|#antiquewhite|Pharo+Moose|
:generate client-
implementation pairs;
:Client+Imp Pairs.csv]
|Git|
:Find class renamings;
:Log file]
|Perl|
:Convert renamings;
:Renamings CSV]
|Pharo|
:Update transactions with
renamings and clients;
:Updated transactions]
|#antiquewhite|R|
:Generate logical-coupling
rules with R (apriori);
:LogicalCoupling.csv]
|Pharo|
:Calculate logical-static 
coupling intersections;
:Stats for set sizes]
stop
@enduml